spring.application.name=hotel_api

spring.datasource.url=jdbc:mariadb://localhost:3306/hotel_database
spring.datasource.username=root
spring.datasource.password=Aykut72.

app.jwt.secret=b45b0131b46f7e83845a3b85dbf00208700d833a5b2d411c748c9b0900f48398
app.jwt.issuer=aykut
app.jwt.access-exp-min=4320

jwt.secret=b45b0131b46f7e83845a3b85dbf00208700d833a5b2d411c748c9b0900f48398
jwt.issuer=aykut
jwt.exp-minutes=4320

app.admin.static-token=1234567890

app.admin.email=aykut@gmail.com
app.admin.password=Aykut123